name: tilashar_test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  touch_ripple_effect: ^2.3.0
  circular_pulse: ^2.0.2
  flutter_card_swiper: ^7.0.0
  material_dialogs: ^1.1.4
  lottie: ^2.7.0
  draggable_home: ^1.0.2
  flutter_sound: ^9.2.13
  dio: ^5.4.1
  clipboard: ^0.1.3
  share_plus: ^7.2.2
  simplytranslate: ^1.2.4
  introduction_screen: ^3.1.12
  shared_preferences: ^2.2.2
  after_layout: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  translator: ^1.0.0
  flutter_quiz_matcher: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/language.png
     - assets/images/grid1.png
     - assets/images/grid2.png
     - assets/images/grid3.png
     - assets/images/grid4.png
     - assets/images/oqylym_first/dumbbell.png
     - assets/images/oqylym_first/guitar.png
     - assets/images/oqylym_first/online-training.png
     - assets/images/oqylym_first/play-with-pet.png
     - assets/images/oqylym_first/read.png
     - assets/images/oqylym_first/reading.png
     - assets/images/oqylym_first/video-calling.png
     - assets/images/oqylym_first/watering-plants.png
     - assets/anim/anim.json
     - assets/anim/someoneLearning.json
     - assets/anim/someoneLearning1.json
     - assets/anim/someoneLearning2.json
     - assets/images/matin_first/monday.jpg
     - assets/images/intro/1.jpg
     - assets/images/intro/2.jpg
     - assets/images/intro/3.jpg
     - assets/rome.png
     - assets/images/second/tesla.jpg

  fonts:
     - family: Bouba Round
       fonts:
         - asset: assets/fonts/bouba_round/BR-Thin.otf
           weight: 100
         - asset: assets/fonts/bouba_round/BR-Light.otf
           weight: 300
         - asset: assets/fonts/bouba_round/BR-Regular.otf
           weight: 400
         - asset: assets/fonts/bouba_round/BR-Medium.otf
           weight: 500
         - asset: assets/fonts/bouba_round/BR-Bold.otf
           weight: 700
         - asset: assets/fonts/bouba_round/BR-Black.otf
           weight: 900
           style: normal
     - family: Roni
       fonts:
         - asset: assets/fonts/roni/Roni.ttf
     - family: Cera Round Pro
       fonts:
         - asset: assets/fonts/cera_round_pro/CRP-Thin.otf
           weight: 100
         - asset: assets/fonts/cera_round_pro/CRP-Light.otf
           weight: 300
         - asset: assets/fonts/cera_round_pro/CRP-Regular.otf
           weight: 400
         - asset: assets/fonts/cera_round_pro/CRP-Medium.otf
           weight: 500
         - asset: assets/fonts/cera_round_pro/CRP-Bold.otf
           weight: 700
         - asset: assets/fonts/cera_round_pro/CRP-Black.otf
           weight: 900
           style: normal

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21